import Head from 'next/head'
import Questao from '../../components/Questao'
import QuestaoModel from '../../model/questao'
import RespostaModel from '../../model/resposta'
import { useState } from 'react'
import Botao from '../../components/Botao'

export default function Home() {

  const questaoMock = new QuestaoModel(1,'Melhor Cor?', [ 
    RespostaModel.errada('Verde'),
    RespostaModel.errada('Azul'),
    RespostaModel.errada('Vermelha'),
    RespostaModel.certa('Preta')
  ])

  function onResponse(indice:number){
    console.log(indice)
    setQuestao(questao.responderCom(indice))
  }

  function tempoEsgotado(){
    if(!questao.respondida){
      setQuestao(questao.responderCom(-1))
    }
  }

  const [questao, setQuestao] = useState(questaoMock)

  return (
    <>
      <Head>
        <title>Quizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100vh'
        }}>
          <Questao valor={questao} onResponse={onResponse} tempoEsgotado={tempoEsgotado}/>
          <Botao texto='Próxima'/>
        </div>
      </main>
    </>
  )
}
