import Head from 'next/head'
import QuestaoModel from '../../model/questao'
import { useEffect, useState } from 'react'
import Questionario from '../../components/Questionario'
import { useRouter } from 'next/router'


const BASE_URL = 'https://projeto-quiz-psi.vercel.app//api'

export default function Home() {

  const router = useRouter()


  const [idsDasQuestoes, setIdsDasQuestoes] = useState<number[]>([])
  const [questao, setQuestao] = useState<QuestaoModel>()
  const [respostasCertas, setRespostasCertas] = useState<number>(0)

  async function loadIds() {
    const resp = await fetch(`${BASE_URL}/questionario`)
    const idsDasQuestoes = await resp.json()
    setIdsDasQuestoes(idsDasQuestoes)
  }

  async function loadQuestion(idQuestao: number) {
    const resp = await fetch(`${BASE_URL}/questoes/${idQuestao}`)
    const json = await resp.json()
    const novaQuestao = QuestaoModel.fromObject(json)
    setQuestao(novaQuestao)
  }

  useEffect(() => {
    loadIds()
  }, [])

  useEffect(() => {
    idsDasQuestoes.length > 0 && loadQuestion(idsDasQuestoes[0])
  }, [idsDasQuestoes])

  useEffect(() => {
    console.log(respostasCertas)
  }, [respostasCertas])

  function onResponse(questaoRespondida: QuestaoModel) {
    setQuestao(questaoRespondida)
    setRespostasCertas(respostasCertas + (questaoRespondida.acertou ? 1 : 0))
  }

  function idProximaPergunta() {
    if (questao) {
      const proximoIndice = idsDasQuestoes.indexOf(questao.id) + 1
      return idsDasQuestoes[proximoIndice]
    }
  }

  function irPraProximoPasso() {
    const proximoId = idProximaPergunta()
    proximoId ? irPraProximaQuestao(proximoId) : finalizar()
  }

  function irPraProximaQuestao(proximoId: number) {
    loadQuestion(proximoId)
  }

  function finalizar() {
    router.push({
      pathname: '/resultado',
      query: {
        total: idsDasQuestoes.length,
        certas: respostasCertas
      }
    })
  }

  return (
    <>
      <Head>
        <title>Quizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {questao ? <Questionario
            questao={questao}
            ultima={idProximaPergunta() === undefined}
            onResponse={onResponse}
            irPraProximoPasso={irPraProximoPasso} />
            : false}
        </div>
      </main>
    </>
  )
}
